!------------------------ BEGIN gckpp_rates.f90 BEGIN ------------------------
! @file gckpp_rates.f90                                                       
! @author yifanwu                                                             
! @date 2014-05-02 14:22:00.329131                                            
! @brief Reaction rate calculation and utility functions                      
!                                                                             
! Reaction rate calculation and utility functions                             
!                                                                             
! This file was generated by Kppa: http://www.paratools.com/Kppa              
!-----------------------------------------------------------------------------


MODULE gckpp_rates

  USE gckpp_parameters

  IMPLICIT NONE




  CONTAINS

!------------------------------------ ARR ------------------------------------
! @param[in]     a0   None                                                    
! @param[in]     b0   None                                                    
! @param[in]     c0   None                                                    
! @param[in]     temp Temperature                                             
!-----------------------------------------------------------------------------
  REAL(8) FUNCTION ARR(a0, b0, c0, temp)
    IMPLICIT NONE

    REAL(8), INTENT(IN) :: a0
    REAL(8), INTENT(IN) :: b0
    REAL(8), INTENT(IN) :: c0
    REAL(8), INTENT(IN) :: temp

        ARR = a0 * (temp/300.0)**c0 * EXP(-b0/temp)
  END FUNCTION ARR


!------------------------------------ ARR2 -----------------------------------
! @param[in]     a0   None                                                    
! @param[in]     b0   None                                                    
! @param[in]     temp Temperature                                             
!-----------------------------------------------------------------------------
  REAL(8) FUNCTION ARR2(a0, b0, temp)
    IMPLICIT NONE

    REAL(8), INTENT(IN) :: a0
    REAL(8), INTENT(IN) :: b0
    REAL(8), INTENT(IN) :: temp

        ARR2 = a0 * EXP(b0/temp)
  END FUNCTION ARR2


!------------------------------------ EP2 ------------------------------------
! @param[in]     a0   None                                                    
! @param[in]     c0   None                                                    
! @param[in]     a2   None                                                    
! @param[in]     c2   None                                                    
! @param[in]     a3   None                                                    
! @param[in]     c3   None                                                    
! @param[in]     temp Temperature                                             
!-----------------------------------------------------------------------------
  REAL(8) FUNCTION EP2(a0, c0, a2, c2, a3, c3, temp)
    IMPLICIT NONE

    REAL(8), INTENT(IN) :: a0
    REAL(8), INTENT(IN) :: c0
    REAL(8), INTENT(IN) :: a2
    REAL(8), INTENT(IN) :: c2
    REAL(8), INTENT(IN) :: a3
    REAL(8), INTENT(IN) :: c3
    REAL(8), INTENT(IN) :: temp

        REAL(8) :: k0, k2, k3

        k0 = a0 * EXP(-c0/temp)
        k2 = a2 * EXP(-c2/temp)
        k3 = a3 * EXP(-c3/temp) * 1.0e6*CFACTOR
        
        EP2 = k0 + k3/(1.0 + k3/k2)
  END FUNCTION EP2


!------------------------------------ EP3 ------------------------------------
! @param[in]     a1   None                                                    
! @param[in]     c1   None                                                    
! @param[in]     a2   None                                                    
! @param[in]     c2   None                                                    
! @param[in]     temp Temperature                                             
!-----------------------------------------------------------------------------
  REAL(8) FUNCTION EP3(a1, c1, a2, c2, temp)
    IMPLICIT NONE

    REAL(8), INTENT(IN) :: a1
    REAL(8), INTENT(IN) :: c1
    REAL(8), INTENT(IN) :: a2
    REAL(8), INTENT(IN) :: c2
    REAL(8), INTENT(IN) :: temp

        REAL(8) :: k1, k2
        
        k1 = a1 * EXP(-c1/temp)
        k2 = a2 * EXP(-c2/temp) * 1.0e6*CFACTOR
        
        EP3 = k1 + k2
  END FUNCTION EP3


!------------------------------------ FALL -----------------------------------
! @param[in]     a0   None                                                    
! @param[in]     b0   None                                                    
! @param[in]     c0   None                                                    
! @param[in]     a1   None                                                    
! @param[in]     b1   None                                                    
! @param[in]     c1   None                                                    
! @param[in]     cf   None                                                    
! @param[in]     temp Temperature                                             
!-----------------------------------------------------------------------------
  REAL(8) FUNCTION FALL(a0, b0, c0, a1, b1, c1, cf, temp)
    IMPLICIT NONE

    REAL(8), INTENT(IN) :: a0
    REAL(8), INTENT(IN) :: b0
    REAL(8), INTENT(IN) :: c0
    REAL(8), INTENT(IN) :: a1
    REAL(8), INTENT(IN) :: b1
    REAL(8), INTENT(IN) :: c1
    REAL(8), INTENT(IN) :: cf
    REAL(8), INTENT(IN) :: temp

        REAL(8) :: k0, k1
    
        k0 = a0 * (temp/300.0)**c0 * EXP(-b0/temp) * 1.0e6*CFACTOR
        k1 = k0 / (a1 * (temp/300.0)**c1 * EXP(-b1/temp))
        
        FALL = (k0/(1.0+k1)) * cf**(1.0/(1.0+LOG10(k1)**2.0))
  END FUNCTION FALL


!------------------------------------ TROE -----------------------------------
! Troe reactions (Stockwell et. al., 1997)                                    
!                                                                             
! @param[in]     k0_300K   None                                               
! @param[in]     n         None                                               
! @param[in]     kinf_300K None                                               
! @param[in]     m         None                                               
! @param[in]     temp      Temperature                                        
! @param[in]     cair      None                                               
!-----------------------------------------------------------------------------
  REAL(8) FUNCTION TROE(k0_300K, n, kinf_300K, m, temp, cair)
    IMPLICIT NONE

    REAL(8), INTENT(IN) :: k0_300K
    REAL(8), INTENT(IN) :: n
    REAL(8), INTENT(IN) :: kinf_300K
    REAL(8), INTENT(IN) :: m
    REAL(8), INTENT(IN) :: temp
    REAL(8), INTENT(IN) :: cair

        REAL(8) :: zt_help, k0_T, kinf_T, k_ratio
    
        zt_help = 300.0/temp
        k0_T = k0_300K * zt_help**n * cair
        kinf_T = kinf_300K * zt_help**m
        k_ratio = k0_T/kinf_T
    
        TROE = k0_T / (1.0 + k_ratio) * 0.6**(1.0/(1.0+LOG10(k_ratio)**2))
  END FUNCTION TROE


!----------------------------------- TROEE -----------------------------------
! Troe equilibrium reactions (Stockwell et. al., 1997)                        
!                                                                             
! @param[in]     a0        None                                               
! @param[in]     b0        None                                               
! @param[in]     k0_300K   None                                               
! @param[in]     n         None                                               
! @param[in]     kinf_300K None                                               
! @param[in]     m         None                                               
! @param[in]     temp      Temperature                                        
! @param[in]     cair      None                                               
!-----------------------------------------------------------------------------
  REAL(8) FUNCTION TROEE(a0, b0, k0_300K, n, kinf_300K, m, temp, cair)
    IMPLICIT NONE

    REAL(8), INTENT(IN) :: a0
    REAL(8), INTENT(IN) :: b0
    REAL(8), INTENT(IN) :: k0_300K
    REAL(8), INTENT(IN) :: n
    REAL(8), INTENT(IN) :: kinf_300K
    REAL(8), INTENT(IN) :: m
    REAL(8), INTENT(IN) :: temp
    REAL(8), INTENT(IN) :: cair

        REAL(8) :: zt_help, k0_T, kinf_T, k_ratio, troe
    
        zt_help = 300.0/temp
        k0_T = k0_300K * zt_help**n * cair
        kinf_T = kinf_300K * zt_help**m
        k_ratio = k0_T/kinf_T 
        troe = k0_T / (1.0 + k_ratio) * 0.6**(1.0/(1.0+ LOG10(k_ratio)**2))
    
        TROEE = a0 * EXP(-b0 / temp) * troe;
  END FUNCTION TROEE


!---------------------------------- Sunlight ---------------------------------
! Calculates sunlight intensity in the range [0,1] as a function of time.     
! Modify this routine to get the correct sunlight values for your model.      
!                                                                             
! @param[in]     time Integration time                                        
! @param[in]     idx  Current grid cell index                                 
!-----------------------------------------------------------------------------
  REAL(8) FUNCTION Sunlight(time, idx)
    IMPLICIT NONE

    REAL(8), INTENT(IN) :: time
    INTEGER, INTENT(IN) :: idx

        REAL, PARAMETER :: PI = 4.0*ATAN(1.0)        ! Pi
        INTEGER, PARAMETER :: daysec = 24 * 3600     ! Seconds per day
        REAL, PARAMETER :: sunrise = 5.5*3600        ! 5:30 local time
        REAL, PARAMETER :: sunset = 19.5*3600        ! 7:30 local time
        REAL :: daily, tmp
        
        daily = time - (INT(time) / daysec) * daysec
        
        ! Estimate sunlight intensity in the range [0,1]
        IF ((daily >= sunrise) .AND. (daily <= sunset)) THEN
            tmp = (2.0 * daily - sunrise - sunset) / (sunset - sunrise);
            IF (tmp > 0) THEN
                tmp = tmp * tmp
            ELSE
                tmp = -tmp * tmp
            END IF
            tmp = 0.5 * (1.0 + COS(PI * tmp))
        ELSE
            tmp = 0.0
        END IF
        Sunlight = tmp
  END FUNCTION Sunlight


!-------------------------------- Temperature --------------------------------
! Calculates temperature (kelvin) as a function of time.                      
! Modify this routine to get the correct temperature values for your model.   
!                                                                             
! @param[in]     time Integration time                                        
! @param[in]     idx  Current grid cell index                                 
!-----------------------------------------------------------------------------
  REAL(8) FUNCTION Temperature(time, idx)
    IMPLICIT NONE

    REAL(8), INTENT(IN) :: time
    INTEGER, INTENT(IN) :: idx

        REAL, PARAMETER :: PI = 4.0*ATAN(1.0)   ! Pi
        REAL, PARAMETER :: mintemp = 280        ! 280 Kelvin ~= 44 Fahrenheit
        REAL, PARAMETER :: maxtemp = 300        ! 300 Kelvin ~= 80 Fahrenheit
        REAL :: tmp
    
        ! Estimate temperature cycling from mintemp to maxtemp
        tmp = SIN(time*PI/(24*3600))
        IF (tmp < 0) THEN
            tmp = mintemp - tmp * (maxtemp-mintemp)
        ELSE
            tmp = mintemp + tmp * (maxtemp-mintemp)
        END IF
        Temperature = tmp
  END FUNCTION Temperature


!----------------------------------- Rates -----------------------------------
! Calculates reaction rate coefficients                                       
!                                                                             
! @param[in]     time Integration time                                        
! @param[in]     idx  Current grid cell index                                 
! @param[out]    rct  Reaction rates                                          
!-----------------------------------------------------------------------------
  SUBROUTINE Rates(time, idx, rct)
    IMPLICIT NONE

    REAL(8), INTENT(IN) :: time
    INTEGER, INTENT(IN) :: idx
    REAL(8), INTENT(OUT) :: rct(331)

    ! Sunlight intensity: 0 to 1 inclusive (uppercase for KPP compatibility) 
    REAL(8) :: SUN
    ! Temperature in kelvin  (uppercase for KPP compatibility) 
    REAL(8) :: TEMP

    SUN = Sunlight(time, idx)
    TEMP = Temperature(time, idx)

    rct(1) = GCARR(3.00E-12, 0.0E+00, -1500.0)
    rct(2) = GCARR(1.70E-12, 0.0E+00, -940.0)
    rct(3) = GCARR(1.00E-14, 0.0E+00, -490.0)
    rct(4) = GCARR(1.20E-13, 0.0E+00, -2450.0)
    rct(5) = GCARR(2.90E-16, 0.0E+00, -1000.0)
    rct(6) = GCARR(1.80E-12, 0.0E+00, 0.0)
    rct(7) = GCARR(6.90E-31, 1.0E+00, 0.0)
    rct(8) = GCARR(4.80E-11, 0.0E+00, 250.0)
    rct(9) = GCARR(1.80E-12, 0.0E+00, 0.0)
    rct(10) = GCARR(3.50E-12, 0.0E+00, 250.0)
    rct(11) = GCARR(3.50E-13, 0.0E+00, 430.0)
    rct(12) = GCARR(2.80E-12, 0.00+00,-1800.0)
    rct(13) = GCARR(1.50E-13, 0.0E+00, 0.0)
    rct(14) = GCARR(2.45E-12, 0.0E+00, -1775.0)
    rct(15) = GCARR(2.80E-12, 0.0E+00, 300.0)
    rct(16) = GCARR(4.10E-13, 0.0E+00, 750.0)
    rct(17) = GCARR(9.50E-14, 0.0E+00, 390.0)
    rct(18) = GCARR(9.50E-14, 0.0E+00, 390.0)
    rct(19) = GCARR(2.66E-12, 0.0E+00, 200.0)
    rct(20) = GCARR(1.14E-12, 0.0E+00, 200.0)
    rct(21) = GCARR(5.50E-12, 0.0E+00, 125.0)
    rct(22) = GCARR(1.80E-30, 3.0E+00, 0.0)
    rct(23) = GCARR(2.41E-14, 0.0E+00, 460.0)
    rct(24) = GCARR(7.00E-31, 2.6E+00, 0.0)
    rct(25) = GCARR(1.80E-11, 0.0E+00, -390.0)
    rct(26) = GCARR(2.00E-31, 3.4E+00, 0.0)
    rct(27) = GCARR(9.52E-05, 3.4E+00, -10900.0)
    rct(28) = GCARR(1.30E-12, 0.0E+00, 380.0)
    rct(29) = GCARR(3.50E-12, 0.0E+00, 0.0)
    rct(30) = GCARR(1.50E-11, 0.0E+00, 170.0)
    rct(31) = GCARR(2.20E-11, 0.0E+00, 0.0)
    rct(32) = GCARR(2.00E-30, 4.4E+00, 0.0)
    rct(33) = GCARR(7.40E-04, 4.4E+00, -11000.0)
    rct(34) = GCARR(2.90E-12, 0.0E+00, -345.0)
    rct(35) = GCARR(4.50E-14, 0.0E+00, -1260.0)
    rct(36) = GCARR(5.80E-16, 0.0E+00, 0.0)
    rct(37) = GCARR(4.40E-12, 0.0E+00, 365.0)
    rct(38) = GCARR(1.40E-12, 0.0E+00, -1900.0)
    rct(39) = GCARR(9.70E-29, 5.6E+00, 0.0)
    rct(40) = GCARR(9.30E-29, 0.0E+00, 14000.0)
    rct(41) = GCARR(8.10E-12, 0.0E+00, 270.0)
    rct(42) = GCARR(8.70E-12, 0.0E+00, -1070.0)
    rct(43) = GCARR(2.60E-12, 0.0E+00, 365.0)
    rct(44) = GCARR(7.60E-12, 0.0E+00, -585.0)
    rct(45) = GCARR(7.60E-12, 0.0E+00, -585.0)
    rct(46) = GCARR(2.90E-12, 0.0E+00, 350.0)
    rct(47) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(48) = GCARR(9.10E-12, 0.0E+00, -405.0)
    rct(49) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(50) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(51) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(52) = GCARR(2.80E-12, 0.0E+00, 300.0)
    rct(53) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(54) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(55) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(56) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(57) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(58) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(59) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(60) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(61) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(62) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(63) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(64) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(65) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(66) = GCARR(2.70E-12, 0.0E+00, 350.0)
    rct(67) = GCARR(2.80E-12, 0.0E+00, -3280.0)
    rct(68) = GCARR(1.60E-12, 0.0E+00, 0.0)
    rct(69) = GCARR(6.00E-12, 0.0E+00, 410.0)
    rct(70) = GCARR(9.00E-28, 8.9E+00, 0.0)
    rct(71) = GCARR(9.00E-29, 0.0E+00, 14000.0)
    rct(72) = GCARR(9.00E-28, 8.9E+00, 0.0)
    rct(73) = GCARR(9.00E-29, 0.0E+00, 14000.0)
    rct(74) = GCARR(6.70E-12, 0.0E+00, 340.0)
    rct(75) = GCARR(6.70E-12, 0.0E+00, 340.0)
    rct(76) = GCARR(6.70E-12, 0.0E+00, 340.0)
    rct(77) = GCARR(6.50E-15, 0.0E+00, 0.0)
    rct(78) = GCARR(1.33E-13, 0.0E+00, 0.0)
    rct(79) = GCARR(3.82E-11, 0.0E+00, -2000.0)
    rct(80) = GCARR(5.92E-13, 0.0E+00, 0.0)
    rct(81) = GCARR(5.92E-13, 0.0E+00, 0.0)
    rct(82) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(83) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(84) = GCARR(8.60E-13, 0.0E+00, 700.0)
    rct(85) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(86) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(87) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(88) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(89) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(90) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(91) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(92) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(93) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(94) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(95) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(96) = GCARR(1.30E-12, 0.0E+00, -25.0)
    rct(97) = GCARR(3.00E-13, 0.0E+00, 0.0)
    rct(98) = GCARR(8.00E-16, 0.0E+00, 0.0)
    rct(99) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(100) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(101) = GCARR(7.50E-13, 0.0E+00, 500.0)
    rct(102) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(103) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(104) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(105) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(106) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(107) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(108) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(109) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(110) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(111) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(112) = GCARR(8.37E-14, 0.0E+00, 0.0)
    rct(113) = GCARR(4.60E-12, 0.0E+00, 70.0)
    rct(114) = GCARR(4.10E-14, 0.0E+00, 0.0)
    rct(115) = GCARR(2.70E-14, 0.0E+00, 0.0)
    rct(116) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(117) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(118) = GCARR(7.40E-13, 0.0E+00, 700.0)
    rct(119) = GCARR(5.20E-13, 0.0E+00, 980.0)
    rct(120) = GCARR(4.30E-13, 0.0E+00, 1040.0)
    rct(121) = GCARR(4.30E-13, 0.0E+00, 1040.0)
    rct(122) = GCARR(4.30E-13, 0.0E+00, 1040.0)
    rct(123) = GCARR(8.00E-27, 3.5E+00, 0.0)
    rct(124) = GCARR(5.50E-15, 0.0E+00, -1880.0)
    rct(125) = GCARR(3.20E-11, 0.0E+00, 0.0)
    rct(126) = GCARR(8.20E-18, 0.0E+00, 0.0)
    rct(127) = GCARR(1.00E-11, 0.0E+00, 0.0)
    rct(128) = GCARR(4.59E-13, 0.0E+00, -1156.0)
    rct(129) = GCARR(1.10E-11, 0.0E+00, 0.0)
    rct(130) = GCARR(1.50E-11, 0.0E+00, 0.0)
    rct(131) = GCARR(1.40E-12, 0.0E+00, -1860.0)
    rct(132) = GCARR(1.40E-12, 0.0E+00, -1860.0)
    rct(133) = GCARR(2.70E-11, 0.0E+00, 390.0)
    rct(134) = GCARR(2.60E-12, 0.0E+00, 610.0)
    rct(135) = GCARR(8.00E-12, 0.0E+00, 380.0)
    rct(136) = GCARR(3.00E-12, 0.0E+00, 0.0)
    rct(137) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(138) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(139) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(140) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(141) = GCARR(1.05E-14, 0.0E+00, -2000.0)
    rct(142) = GCARR(8.50E-16, 0.0E+00, -1520.0)
    rct(143) = GCARR(1.40E-15, 0.0E+00, -2100.0)
    rct(144) = GCARR(3.15E-12, 0.0E+00, -450.0)
    rct(145) = GCARR(2.30E-15, 0.0E+00, 0.0)
    rct(146) = GCARR(1.10E-15, 0.0E+00, 0.0)
    rct(147) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(148) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(149) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(150) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(151) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(152) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(153) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(154) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(155) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(156) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(157) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(158) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(159) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(160) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(161) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(162) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(163) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(164) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(165) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(166) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(167) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(168) = GCARR(3.80E-12, 0.0E+00, 200.0)
    rct(169) = GCARR(1.40E-18, 0.0E+00, 0.0)
    rct(170) = GCARR(3.70E-11, 0.0E+00, 0.0)
    rct(171) = GCARR(6.16E-15, 0.0E+00, -1814.0)
    rct(172) = GCARR(2.50E-12, 0.0E+00, 500.0)
    rct(173) = GCARR(1.80E-12, 0.0E+00, 500.0)
    rct(174) = GCARR(2.00E-13, 0.0E+00, 500.0)
    rct(175) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(176) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(177) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(178) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(179) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(180) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(181) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(182) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(183) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(184) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(185) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(186) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(187) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(188) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(189) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(190) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(191) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(192) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(193) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(194) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(195) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(196) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(197) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(198) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(199) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(200) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(201) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(202) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(203) = GCARR(1.68E-12, 0.0E+00, 500.0)
    rct(204) = GCARR(1.87E-13, 0.0E+00, 500.0)
    rct(205) = GCARR(2.50E-12, 0.0E+00, 500.0)
    rct(206) = GCARR(2.50E-12, 0.0E+00, 500.0)
    rct(207) = GCARR(2.50E-12, 0.0E+00, 500.0)
    rct(208) = GCARR(8.50E-13, 0.0E+00, -2450.0)
    rct(209) = EMISS(ind_NO)
    rct(210) = EMISS(ind_NO2)
    rct(211) = EMISS(ind_CO)
    rct(212) = EMISS(ind_ALK4)
    rct(213) = EMISS(ind_ISOP)
    rct(214) = EMISS(ind_ACET)
    rct(215) = EMISS(ind_PRPE)
    rct(216) = EMISS(ind_C3H8)
    rct(217) = EMISS(ind_C2H6)
    rct(218) = EMISS(ind_MEK)
    rct(219) = EMISS(ind_ALD2)
    rct(220) = EMISS(ind_CH2O)
    rct(221) = EMISS(ind_O3)
    rct(222) = EMISS(ind_HNO3)
    rct(223) = EMISS(ind_CHBR3)
    rct(224) = EMISS(ind_CH2BR2)
    rct(225) = EMISS(ind_BR2)
    rct(226) = DRYLOSS(ind_NO2)
    rct(227) = DRYLOSS(ind_O3)
    rct(228) = DRYLOSS(ind_PAN)
    rct(229) = DRYLOSS(ind_HNO3)
    rct(230) = DRYLOSS(ind_CH2O)
    rct(231) = DRYLOSS(ind_N2O5)
    rct(232) = DRYLOSS(ind_H2O2)
    rct(233) = DRYLOSS(ind_PMN)
    rct(234) = DRYLOSS(ind_PPN)
    rct(235) = DRYLOSS(ind_R4N2)
    rct(236) = DRYLOSS(ind_MVK)
    rct(237) = DRYLOSS(ind_MACR)
    rct(238) = GCARR(3.30E+01, 2.0E-01, 0.0)
    rct(239) = GCARR(4.60E+01, 1.0E-04, 0.0)
    rct(240) = GCARR(6.20E+01, 1.0E-03, 0.0)
    rct(241) = GCARR(1.08E+02, 1.0E-01, 0.0)
    rct(242) = GCARR(1.10E-11, 0.0E+00, -240.0)
    rct(243) = GCARR(1.00E-39, 0.0E+00, 5820.0)
    rct(244) = GCARR(1.90E-13, 0.0E+00, 500.0)
    rct(245) = GCARR(3.30E-31, 4.3E+00, 0.0)
    rct(246) = GCARR(1.70E-11, 0.0E+00, -800.0)
    rct(247) = GCARR(4.50E-12, 0.0E+00, 460.0)
    rct(248) = GCARR(4.80E-12, 0.0E+00, -310.0)
    rct(249) = GCARR(5.50E-12, 0.0E+00, 200.0)
    rct(250) = GCARR(2.40E-12, 0.0E+00, 40.0)
    rct(251) = GCARR(2.80E-14, 0.0E+00, 860.0)
    rct(252) = GCARR(8.80E-12, 0.0E+00, 260.0)
    rct(253) = GCARR(4.90E-11, 0.0E+00, 0.0)
    rct(254) = GCARR(2.10E-11, 0.0E+00, 240.0)
    rct(255) = GCARR(1.70E-11, 0.0E+00, 250.0)
    rct(256) = GCARR(1.60E-11, 0.0E+00, 0.0)
    rct(257) = GCARR(1.70E-11, 0.0E+00, -800.0)
    rct(258) = GCARR(1.30E-11, 0.0E+00, -360.0)
    rct(259) = GCARR(1.66E-10, 0.0E+00, -7000.0)
    rct(260) = GCARR(2.36E-10, 0.0E+00, -6411.0)
    rct(261) = GCARR(8.77E-11, 0.0E+00, -4330.0)
    rct(262) = GCARR(4.20E-31, 2.4E+00, 0.0)
    rct(263) = GCARR(5.20E-31, 3.2E+00, 0.0)
    rct(264) = GCARR(1.35E-12, 0.0E+00, -600.0)
    rct(265) = GCARR(2.00E-12, 0.0E+00, -840.0)
    rct(266) = GCARR(2.35E-12, 0.0E+00, -1300.0)
    rct(267) = GCARR(1.42E+02, 3.0E-01, 0.0)
    rct(268) = GCARR(0.97E+02, 2.0E-01, 0.0)
    rct(269) = GCARR(0.81E+02, 2.0E-01, 0.0)
    rct(270) = GCARR(0.97E+02, 1.0E-01, 0.0)
    rct(271) = GCARR(0.81E+02, 1.0E-01, 0.0)
    rct(272) = GCARR(0.00E+00, 0.0E+00, 0.0)
    rct(273) = GCARR(0.00E+00, 0.0E+00, 0.0)
    rct(274) = GCARR(0.00E+00, 0.0E+00, 0.0)
    rct(275) = GCARR(0.00E+00, 0.0E+00, 0.0)
    rct(276) = PHOTO_1( ind_O3 )
    rct(277) = PHOTO_1( ind_NO2 )
    rct(278) = PHOTO_1( ind_H2O2 )
    rct(279) = PHOTO_1( ind_MP )
    rct(280) = PHOTO_1( ind_CH2O )
    rct(281) = PHOTO_2( ind_CH2O )
    rct(282) = PHOTO_1( ind_HNO3 )
    rct(283) = PHOTO_1( ind_HNO2 )
    rct(284) = PHOTO_1( ind_HNO4 )
    rct(285) = PHOTO_2( ind_NO3 )
    rct(286) = PHOTO_1( ind_NO3 )
    rct(287) = PHOTO_2( ind_N2O5 )
    rct(288) = PHOTO_1( ind_N2O5 )
    rct(289) = PHOTO_2( ind_HNO4 )
    rct(290) = PHOTO_2( ind_ALD2 )
    rct(291) = PHOTO_1( ind_ALD2 )
    rct(292) = PHOTO_1( ind_PAN )
    rct(293) = PHOTO_1( ind_RCHO )
    rct(294) = PHOTO_1( ind_ACET )
    rct(295) = PHOTO_2( ind_ACET )
    rct(296) = PHOTO_1( ind_MEK )
    rct(297) = PHOTO_1( ind_GLYC )
    rct(298) = PHOTO_1( ind_GLYX )
    rct(299) = PHOTO_2( ind_GLYX )
    rct(300) = PHOTO_1( ind_MGLY )
    rct(301) = PHOTO_2( ind_MGLY )
    rct(302) = PHOTO_1( ind_MVK )
    rct(303) = PHOTO_2( ind_MVK )
    rct(304) = PHOTO_3( ind_MVK )
    rct(305) = PHOTO_1( ind_MACR )
    rct(306) = PHOTO_2( ind_MACR )
    rct(307) = PHOTO_1( ind_HAC )
    rct(308) = PHOTO_1( ind_INPN )
    rct(309) = PHOTO_1( ind_PRPN )
    rct(310) = PHOTO_1( ind_ETP )
    rct(311) = PHOTO_1( ind_RA3P )
    rct(312) = PHOTO_1( ind_RB3P )
    rct(313) = PHOTO_1( ind_R4P )
    rct(314) = PHOTO_1( ind_PP )
    rct(315) = PHOTO_1( ind_RP )
    rct(316) = PHOTO_1( ind_GP )
    rct(317) = PHOTO_1( ind_RIP )
    rct(318) = PHOTO_1( ind_IAP )
    rct(319) = PHOTO_1( ind_ISNP )
    rct(320) = PHOTO_1( ind_VRP )
    rct(321) = PHOTO_1( ind_MRP )
    rct(322) = PHOTO_1( ind_MAOP )
    rct(323) = PHOTO_1( ind_R4N2 )
    rct(324) = PHOTO_1( ind_MAP )
    rct(325) = PHOTO_1( ind_Br2 )
    rct(326) = PHOTO_1( ind_BrO )
    rct(327) = PHOTO_1( ind_HOBr )
    rct(328) = PHOTO_1( ind_BrNO3 )
    rct(329) = PHOTO_2( ind_BrNO3 )
    rct(330) = PHOTO_1( ind_BrNO2 )
    rct(331) = PHOTO_1( ind_CHBr3 )
  END SUBROUTINE Rates



END MODULE gckpp_rates
!-------------------------- END gckpp_rates.f90 END --------------------------
